config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: "registrations"}
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :attendances
  # Defines the root path route ("/")
  get '/users/:id' => 'users#show', as: 'user'
  get '/users/:id/attended_events' => 'users#show_events_attended', as: 'show_events_attended'

  resources :events
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true
	validates :description, :date, :location, presence: true

	has_many :attendances
	has_many :attendees, through: :attendances, source: :user
	belongs_to :creator, class_name: "User"

	scope :past, -> { where('date < ?', Date.today) }
	scope :upcoming, -> { where('date >= ?', Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event
  has_many :created_events, foreign_key: "creator_id", class_name: "Event", dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

    def new
        @event = Event.find(params[:id])
    end

    def create
        @event = Event.find(params[:id])
        @event.attendees << current_user
        flash[:notice] = "Registration was successfull"
        redirect_to root_path
    end

    def destroy
        @event = Event.find(params[:id])
        @event.attendees.delete(current_user)
        flash[:notice] = "you have cancelled your registration"
        redirect_to root_path
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :set_event, only: [ :show, :edit, :update, :destroy ]
    before_action :authenticate_user!, except: [:index]

    def index
        @events = Event.all.order("created_at DESC")
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = current_user.created_events.build
    end

    def create
        @event = current_user.created_events.build(event_params)

        if @event.save
            redirect_to root_path, notice: "Event was successfully created."
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        if @event.update(@event)
            redirect_to event_url(@event), notice: "Event was successfully updated."
        else
            render :edit, status: :unprocessable_entity 
        end
    end

    def destroy
        @event.destroy
        redirect_to events_url, notice: "Event was successfully destroyed."
    end

    private

    def set_event
        @event = Event.find(params[:id])
    end

    def event_params
        params.require(:event).permit(:title, :description, :date, :location)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
        def sign_up_params
            params.require(:user).permit(:username, :email, :password, :password_confirmation)
        end

        def account_update_params
            params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @attended_events = current_user.attended_events
    end

    def show_events_attended
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/show.html.erb
<h2>Attended Events</h2>
<% @attended_events.each do | attended | %>
    <small><%= attended.title %></small>
<% end %>

app/views/events/_attended_event.html.erb
<div class="column is-one-quarter">
    <h2 class="title is-5">Attended Events<h2>
    <nav class="panel">
        <%current_user.attended_events.each do | attended |%>
            <small><%= attended.title %></small><br>
        <% end %>
    </nav>
</div>

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= event.title %></strong><br>
        </p>

        <p>
          <%= event.description %>
        </p>

        <p>
          <small><%= event.date %></small>
          
        </p>

        <p>
          <small><%= event.location %></small>
        </p>
      </div>
    </div>
  </article>

</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <div class="control">
      <%= f.input :title, label: "Event Title", input_html: {class: "input"},
      wrapper: false,
      label_html: {class: "label"},
      autofocus: true %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :description, label: "Description", input_html: {class: "textarea"},
      wrapper: false,
      label_html: {class: "label"},
      autofocus: true %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :date, label: "Date", input_html: {class: "date"},
      wrapper: false,
      label_html: {class: "label"},
      autofocus: true %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :location, label: "Location", input_html: {class: "input"},
      wrapper: false,
      label_html: {class: "label"},
      autofocus: true %>
    </div>
  </div>

    <%= f.submit :submit, class: "button is-primary"%>
<% end %>

app/views/events/_navbar.html.erb
<nav class="navbar is-dark">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <h1 class="title is-5">Eventer</h1>
    <% end %>

    <div class="navbar-burger burger is-active" data-target="navbarExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExample" class="navbar-menu is-active">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">

            <% if user_signed_in? %>

              <p class="control">
                <%= link_to "Create Event", new_event_path, class: "button is-info is-inverted" %>
              </p>

              <p class="control">
                <%= link_to current_user.username, edit_user_registration_path, class: "button is-dark" %>
              </p>

              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-dark" %>
              </p>

            <% else %>

              <p class="control">
                <%= link_to "Create Event", new_user_session_path, class: "button is-info is-inverted" %>
              </p>

              <p class="control">
                <%= link_to 'Log In', new_user_session_path, class: "button is-dark"  %>
              </p>

              <p class="control">
                <%= link_to 'Sign Up', new_user_registration_path, class: "button is-dark"  %>
              </p>

            <% end %>

          </div>
        </div>
      </div>
  </div>
</nav>

app/views/events/_past_event.html.erb
<div class="column">
    <h2 class="title is-4">Past Events</h2>
    <div class="scrolling-wrapper">
            <div class="columns">
                <% @events.past.each do |event| %>
                    <div class="column is-3">
                        <%= link_to event, class: "navbar-item" do %>
                            <div class="box">
                                <article class="media">
                                    <div class="media-content">
                                        <strong><%= event.title %></strong>
                                        <p><%= event.description.truncate_words(20) %></p><br>
                                        <small><%= event.date %></small><br>
                                        <small><%= event.location %></small>
                                    </div>
                                    
                                </article>
                            </div>
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/events/_upcoming_event.html.erb
<div class="column">
    <h2 class="title is-4">Upcoming Events</h2>
    <div class="scrolling-wrapper">
            <div class="columns">
                <% @events.upcoming.each do |event| %>
                    <div class="column is-3">
                        <%= link_to event, class: "navbar-item" do %>
                            <div class="box">
                                <article class="media">
                                    <div class="media-content">
                                        <strong><%= event.title %></strong>
                                        <p><%= event.description.truncate_words(20) %></p><br>
                                        <p class="is-danger"><%= event.date %></p>
                                        <small><%= event.location %></small>
                                    </div>
                                    
                                </article>
                            </div>
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/events/edit.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title is-1">Editing Event</h1>

        <%= render "form", event: @event %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-button">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Cancel', event_path, class: "button is-dark" %>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/events/index.html.erb
<section class="section">
	<div class="container">
		<div class="columns">
			<%= render 'upcoming_event'%>
			<%= render 'past_event'%>
			<% if user_signed_in? %>
				<%= render 'attended_event'%>
			<% end %>
		</div>
	</div>
</section>

app/views/events/new.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title is-1">New Event</h1>

        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-button">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Cancel', root_path, class: "button is-dark" %>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/events/show.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        
        <%= render @event %>
      </div>
    </div>
  </div>
</div>

<div class="column">
  <nav class="navbar is-fixed-button">
    <div class="navbar-menu">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
             <%= link_to 'Back', root_path, class: "button is-dark" %>
          </p>

          <% if current_user == @event.creator %>
            <p class="control">
               <%= link_to 'Edit', edit_event_path(@event), class: "button is-primary" %>
            </p>

            <p class="control">
              <%= link_to "Delete this event", @event, method: :delete, data: {confirm: 'Are you sure you want to delete this event?'}, class: "button is-danger" %>
            </p>
          <% elsif !@event.attendees.include?(current_user)%>
            <p class="control">
              <%= button_to 'Attend', attendances_path(:user_id => current_user.id, :id => @event.id), class: "button is-primary",method: :post %>
            </p>

          <% else %>
            <p class="control">
              <%= button_to 'Cancel Attendance', attendance_path, method: :delete, data: {confirm: 'Are you sure you want to cancel your attendance to this event?'}, class: "button is-danger" %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
    <br><br>
    <h2 class="content is-large">Registered Users for the Event</h2>
    <% @event.attendees.each do | attendee| %>
        <strong><%= attendee.username %></strong>
    <% end %>

</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% if flash[:notice] %>
    <div class="notification is-primary global-noification">
      <p class="notice"><%= notice %></p>
    </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger global-noification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= render 'events/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/users/_show_events_attended.html.erb
<h2>Attended Events</h2>

<% @events_attended.each do | attended |%>
    <small><%= attended.title %><small>
<% end %>